#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/fly.h"
#include "images/flyswatter.h"
#include "images/gameover.h"
#include "images/winscreen.h"
#include "images/startscreen.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  unsigned short bgcolor = BLACK;
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  struct fly *fp, *ofp;
  struct fly_state cfs, pfs;
  struct flyswatter *fsp, *ofsp;
  struct flyswatter_state cfss, pfss;

  fsp = &cfss.flyswatters;
  fsp->row = HEIGHT - FLYSWATTER_HEIGHT;
  fsp->col = 0;

  fp = &cfs.flies;
  fp->row = 0;
  fp->col = 0;
  fp->row_dist = 1;
  fp->col_dist = 1;


  int timer = 0;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:;

        // state = ?
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          fsp = &cfss.flyswatters;
          fsp->row = HEIGHT - FLYSWATTER_HEIGHT;
          fsp->col = 0;

          fp = &cfs.flies;
          fp->row = 0;
          fp->col = 0;
          fp->row_dist = 1;
          fp->col_dist = 1;
          timer = 6000;

          state = PLAY;
        }
        if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons) && KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = WIN;
        }
        waitForVBlank();
        drawFullScreenImageDMA(startscreen);
        /*fillScreenDMA(bgcolor);
        drawString(50, WIDTH / 2 - 36, "WELCOME!!!!", CYAN);
        drawString(100, WIDTH / 2 - 63, "PRESS ENTER TO START", YELLOW);*/
        break;
      case PLAY:;

        // state = ?
        pfs = cfs;
        fp = &cfs.flies;
        fp->row += fp->row_dist;
        fp->col += fp->col_dist;

        pfss = cfss;
        fsp = &cfss.flyswatters;
        fsp->row += 0;
        fsp->col += 0;

        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }
        
        if (KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons)){
          fsp->row -= 3;
          if (fsp->row < 0) {
            fsp->row = 0;
          }
        }
        if (KEY_JUST_PRESSED(BUTTON_DOWN, currentButtons, previousButtons)){
          fsp->row += 3;
          if (fsp->row > HEIGHT - FLYSWATTER_HEIGHT) {
            fsp->row = HEIGHT - FLYSWATTER_HEIGHT;
          }
        }
        if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons)){
          fsp->col -= 3;
          if (fsp->col < 0) {
            fsp->col = 0;
          }
        }
        if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)){
          fsp->col += 3;
          if (fsp->col > WIDTH - FLYSWATTER_WIDTH) {
            fsp->col = WIDTH - FLYSWATTER_WIDTH;
          }
        }

        if(fp->row < 0) {
          fp->row = 0;
          fp->row_dist = -fp->row_dist;
        }
        if(fp->row > HEIGHT - FLY_HEIGHT) {
          fp->row = HEIGHT - FLY_HEIGHT;
          fp->row_dist = -fp->row_dist;
        }
        if(fp->col < 0) {
          fp->col = 0;
          fp->col_dist = -fp->col_dist;
        }
        if(fp->col > WIDTH - FLY_WIDTH) {
          fp->col = WIDTH - FLY_WIDTH;
          fp->col_dist = -fp->col_dist;
        }

        if(timer == 0) {
          state = LOSE;
        }

        if(((fp->row > fsp->row) && (fp->row < fsp->row + FLYSWATTER_HEIGHT)) && ((fp->col > fsp->col) && (fp->col < fsp->col + FLYSWATTER_WIDTH))) {
          state = WIN;
        }
        
        

        timer--;
        

        waitForVBlank();
        fillScreenDMA(bgcolor);
        ofp = &pfs.flies;
        drawRectDMA(ofp->row, ofp->col, FLY_WIDTH, FLY_HEIGHT, bgcolor);
        fp = &cfs.flies;
        drawImageDMA(fp->row, fp->col, FLY_WIDTH, FLY_HEIGHT,fly);
        ofsp = &pfss.flyswatters;
        drawRectDMA(ofsp->row, ofsp->col, FLYSWATTER_WIDTH, FLYSWATTER_HEIGHT, bgcolor);
        fsp = &cfss.flyswatters;
        drawImageDMA(fsp->row, fsp->col, FLYSWATTER_WIDTH, FLYSWATTER_HEIGHT, flyswatter);


        int onScreenTimer = timer / 60;
        char buffer[51];
        sprintf(buffer, "Timer: %d", onScreenTimer);
        drawString(150, 180, buffer, GREEN);

        break;
      case WIN:;

        // state = ?
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }
        waitForVBlank();
        drawFullScreenImageDMA(winscreen);
        break;
      case LOSE:;

        // state = ?
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }
        waitForVBlank();
        drawFullScreenImageDMA(gameoverscreen);
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
